/* 게시판 */
DROP TABLE BOARDMASTER 
	CASCADE CONSTRAINTS;

/* 사용자 */
DROP TABLE USERS 
	CASCADE CONSTRAINTS;

/* 게시글 */
DROP TABLE BOARD 
	CASCADE CONSTRAINTS;

/* 댓글 */
DROP TABLE REPLY 
	CASCADE CONSTRAINTS;

/* 첨부파일 */
DROP TABLE ATTACHFILE 
	CASCADE CONSTRAINTS;

/* 게시판 시퀀스 */
DROP SEQUENCE seq_BOARDMASTER;

/* 게시글 시퀀스 */
DROP SEQUENCE seq_BOARD;

/* 댓글 시퀀스 */
DROP SEQUENCE seq_REPLY;

/* 첨부파일 시퀀스 */
DROP SEQUENCE seq_ATTACHFILE;

/* 게시판 시퀀스 */
CREATE SEQUENCE seq_BOARDMASTER;

/* 게시글 시퀀스 */
CREATE SEQUENCE seq_BOARD;

/* 댓글 시퀀스 */
CREATE SEQUENCE seq_REPLY;

/* 첨부파일 시퀀스 */
CREATE SEQUENCE seq_ATTACHFILE;

/* 게시판 */
CREATE TABLE BOARDMASTER (
	bm_id NUMBER NOT NULL, /* 게시판ID */
	bm_nm VARCHAR(150) NOT NULL, /* 게시판이름 */
	act_yn VARCHAR2(1) DEFAULT 'Y' NOT NULL, /* 활성여부 */
	reg_id VARCHAR2(20) NOT NULL, /* 작성자 */
	reg_dt DATE NOT NULL /* 작성일시 */
);

COMMENT ON TABLE BOARDMASTER IS '게시판';

COMMENT ON COLUMN BOARDMASTER.bm_id IS '게시판ID';

COMMENT ON COLUMN BOARDMASTER.bm_nm IS '게시판이름';

COMMENT ON COLUMN BOARDMASTER.act_yn IS '활성여부';

COMMENT ON COLUMN BOARDMASTER.reg_id IS '작성자';

COMMENT ON COLUMN BOARDMASTER.reg_dt IS '작성일시';

CREATE UNIQUE INDEX PK_BOARDMASTER
	ON BOARDMASTER (
		bm_id ASC
	);

ALTER TABLE BOARDMASTER
	ADD
		CONSTRAINT PK_BOARDMASTER
		PRIMARY KEY (
			bm_id
		);

/* 사용자 */
CREATE TABLE USERS (
	userid VARCHAR2(20) NOT NULL, /* 사용자ID */
	pass VARCHAR(20), /* 비밀번호 */
	usernm VARCHAR(20), /* 사용자이름 */
	alias VARCHAR(20) /* 별명 */
);

COMMENT ON TABLE USERS IS '사용자';

COMMENT ON COLUMN USERS.userid IS '사용자ID';

COMMENT ON COLUMN USERS.pass IS '비밀번호';

COMMENT ON COLUMN USERS.usernm IS '사용자이름';

COMMENT ON COLUMN USERS.alias IS '별명';

CREATE UNIQUE INDEX PK_USERS
	ON USERS (
		userid ASC
	);

ALTER TABLE USERS
	ADD
		CONSTRAINT PK_USERS
		PRIMARY KEY (
			userid
		);

/* 게시글 */
CREATE TABLE BOARD (
	id NUMBER NOT NULL, /* 게시글ID */
	bm_id NUMBER NOT NULL, /* 게시판ID */
	p_id NUMBER, /* 부모게시글번호 */
	title VARCHAR2(300) NOT NULL, /* 제목 */
	cont CLOB NOT NULL, /* 내용 */
	del_yn VARCHAR2(1) DEFAULT 'Y' NOT NULL, /* 삭제여부 */
	reg_id VARCHAR2(20) NOT NULL, /* 작성자 */
	reg_dt DATE NOT NULL /* 작성일시 */
);

COMMENT ON TABLE BOARD IS '게시글';

COMMENT ON COLUMN BOARD.id IS '게시글ID';

COMMENT ON COLUMN BOARD.bm_id IS '게시판ID';

COMMENT ON COLUMN BOARD.p_id IS '부모게시글번호';

COMMENT ON COLUMN BOARD.title IS '제목';

COMMENT ON COLUMN BOARD.cont IS '내용';

COMMENT ON COLUMN BOARD.del_yn IS '삭제여부';

COMMENT ON COLUMN BOARD.reg_id IS '작성자';

COMMENT ON COLUMN BOARD.reg_dt IS '작성일시';

CREATE UNIQUE INDEX PK_BOARD
	ON BOARD (
		id ASC
	);

ALTER TABLE BOARD
	ADD
		CONSTRAINT PK_BOARD
		PRIMARY KEY (
			id
		);

/* 댓글 */
CREATE TABLE REPLY (
	id NUMBER NOT NULL, /* 댓글ID */
	b_id NUMBER NOT NULL, /* 게시글ID */
	cont VARCHAR2(1500) NOT NULL, /* 내용 */
	reg_id VARCHAR2(20) NOT NULL, /* 작성자 */
	reg_dt DATE NOT NULL /* 작성일시 */
);

COMMENT ON TABLE REPLY IS '댓글';

COMMENT ON COLUMN REPLY.id IS '댓글ID';

COMMENT ON COLUMN REPLY.b_id IS '게시글ID';

COMMENT ON COLUMN REPLY.cont IS '내용';

COMMENT ON COLUMN REPLY.reg_id IS '작성자';

COMMENT ON COLUMN REPLY.reg_dt IS '작성일시';

CREATE UNIQUE INDEX PK_REPLY
	ON REPLY (
		id ASC
	);

ALTER TABLE REPLY
	ADD
		CONSTRAINT PK_REPLY
		PRIMARY KEY (
			id
		);

/* 첨부파일 */
CREATE TABLE ATTACHFILE (
	id NUMBER NOT NULL, /* 첨부파일ID */
	nm VARCHAR2(500) NOT NULL, /* 첨부파일명 */
	b_id NUMBER NOT NULL /* 게시글ID */
);

COMMENT ON TABLE ATTACHFILE IS '첨부파일';

COMMENT ON COLUMN ATTACHFILE.id IS '첨부파일ID';

COMMENT ON COLUMN ATTACHFILE.nm IS '첨부파일명';

COMMENT ON COLUMN ATTACHFILE.b_id IS '게시글ID';

CREATE UNIQUE INDEX PK_ATTACHFILE
	ON ATTACHFILE (
		id ASC
	);

ALTER TABLE ATTACHFILE
	ADD
		CONSTRAINT PK_ATTACHFILE
		PRIMARY KEY (
			id
		);

ALTER TABLE BOARDMASTER
	ADD
		CONSTRAINT FK_USERS_TO_BOARDMASTER
		FOREIGN KEY (
			reg_id
		)
		REFERENCES USERS (
			userid
		);

ALTER TABLE BOARD
	ADD
		CONSTRAINT FK_USERS_TO_BOARD
		FOREIGN KEY (
			reg_id
		)
		REFERENCES USERS (
			userid
		);

ALTER TABLE BOARD
	ADD
		CONSTRAINT FK_BOARDMASTER_TO_BOARD
		FOREIGN KEY (
			bm_id
		)
		REFERENCES BOARDMASTER (
			bm_id
		);

ALTER TABLE BOARD
	ADD
		CONSTRAINT FK_BOARD_TO_BOARD
		FOREIGN KEY (
			p_id
		)
		REFERENCES BOARD (
			id
		);

ALTER TABLE REPLY
	ADD
		CONSTRAINT FK_USERS_TO_REPLY
		FOREIGN KEY (
			reg_id
		)
		REFERENCES USERS (
			userid
		);

ALTER TABLE REPLY
	ADD
		CONSTRAINT FK_BOARD_TO_REPLY
		FOREIGN KEY (
			b_id
		)
		REFERENCES BOARD (
			id
		);

ALTER TABLE ATTACHFILE
	ADD
		CONSTRAINT FK_BOARD_TO_ATTACHFILE
		FOREIGN KEY (
			b_id
		)
		REFERENCES BOARD (
			id
		);